### PR TITLE
feat: add AuthState via reducer (#583) 

### PR DESCRIPTION
**Pull request by pamapa**
The implementation covers the current state. It lays the the ground work for error handling. Same with `isAuthenticated`.

### CODE REVIEW

**Comment by pamapa** [comment]
for some test we can no longer call `render` as this produces an endless test loop, which is a test issue. I have fixed that using the same mechanism as used in auth0-react:
- renderHook
- waitForNextUpdate

**Comment by pamapa** [comment]
i don't know why the coverage is failing. `useAuth` is new tested as well...

ready to merge

**Comment by pamapa** [comment]
test coverage fixed by adding `useAuth.test.tsx`

ready for review + merge

**Comment by pamapa** [comment]
i just noticed that after this is merged `if (isMountedRef.current)` is no longer needed. I will drop it in a following merge request. It does not harm behaviour...

**Comment by cobraz** [comment]
For reference, this is a breaking change.

**Comment by pamapa** [comment]
maybe before making a new release, let me fix #587 + #586 as well...

**Comment by ryancole** [comment]
@pamapa can you please provide an explanation of the value added by this patch? Why the introduction of a reducer? What issue is this patch addressing or what feature is this patch adding? Thank you.

**Comment by pamapa** [comment]
This merge request is a 1:1 replacing of the current features.

This patch prepares the ground to implemented a proper error handling, which is currently missing. In a next merge request i will provide the additional `error` + `isAuthenticated` flags in the auth state.
Also it makes handling auth states much more easy, as you wont need any `if (isMountedRef.current)`. Are you sure this is correct (without the `if`)?:
https://github.com/bjerkio/oidc-react/blob/dffb3996c928fe0d125e4b53d8b91b47a2137613/src/AuthContext.tsx#L92

Please merge this as is.

**Comment by pamapa** [comment]
To make it more clear, i have now adapted the patch to remove the `isMountedRef` already now and not later.

Please merge this as is.

**Comment by ryancole** [comment]
@pamapa Can you explain why you introduced reducers to the code instead of `useState` hooks? Was there something that could only be achieved using reducers or are they what you're more comfortable with? I'm just thinking about code clarity going forward and the cost of introducing a new style of state management with reducers.

**Comment by pamapa** [comment]
@ryancole The main idea about the auth state is that those fields inside the auth state depend on each other, if you change one it will affect others. Using reducers is much easier in that regard.

```
const [isLoading, setIsLoading] = useState(true);
const [userData, setUserData] = useState<User | null>(null);
// in short also:
const [isAuthenticated, setIsAuthenticated] = useState(false);
const [error, setError] = useState<Error>(null);
...
// this kind of block must be done at multiple places in different cominations
setUserData(user) // affetcs others:
setIsLoading(false)
setIsAuthenticated(true)
// error must remain
```

-> reducer is the way to go.

For me using reducers is inescapable for this kind of library.
BTW: auth0.react is using reducers as well.

**Comment by ryancole** [comment]
@pamapa OK, so it's a preference thing. I'm fine with reducers, personally. It's @cobraz call to make.

**Review by ryancole — APPROVED** [review]
I'm good with it.

**Comment by pamapa** [comment]
@ryancole thanks for the review, i do no think that application must be adapted regarding this change.

@cobraz please merge this now, so that we can proceed with error handling :-)

**Comment by pamapa** [comment]
@cobraz i guess you are busy with other stuff, friendly remainder to merge this

**Comment by pamapa** [comment]
please merge this finally

**Comment by cobraz** [comment]
> please merge this finally

We'll be reviewing this and get back to you. We're doing the best we can, but as this is considered a breaking change (and as @ryancole pointed out, a new style as well) we're not taking it as lightly (therefore things move a bit more slowly).

**Comment by cobraz** [comment]
@pamapa We are still looking into this, but considering you've closed all your issues (and created your own package) I don't know if you want to anymore?

Would love your feedback!

**Comment by pamapa** [comment]
@cobraz this took too far long for me and my team. Additional I wanted to do more than this merge request. So we created our own library. Now i have all goodies I wanted first hand. I tried to avoid creating a new library that but it did not work out.
Iff you would have merged this, i would have provided more than 50% of this library code and still no permission to review + merge stuff, which i would not like anyway.

Thus i am no longer interested into merging this. Feel free to port code parts from my library (https://github.com/pamapa/react-oidc-context), into your code. Both libraries are licensed under MIT.

**Pull request closed without merging**
