### PR TITLE
Add postLogoutRedirectUri option.

### PR DESCRIPTION
**Pull request by pseudoramble**
Adds the post logout redirect URI to be specified, as discussed in https://github.com/bjerkio/oidc-react/issues/327. It falls back to the redirect URI if not given.

### CODE REVIEW

**Comment by pseudoramble** [comment]
By the way, I have tried to run the recommended command for updating documentation but ran into this error. I'm not quite sure what to make of it honestly, but I'm happy to try again if there's any suggestions on what to check. 

```
$ yarn generate-docs
yarn run v1.22.10
$ typedoc --out docs src
Info: Loaded plugin typedoc-plugin-markdown
Error: Tried to set an option (module) that was not declared.
Error: Tried to set an option (mode) that was not declared.
Error: Tried to set an option (target) that was not declared.
Error: Tried to set an option (hideSources) that was not declared.
Error: Tried to set an option (includeDeclarations) that was not declared.
error Command failed with exit code 1.
```

**Comment by cobraz** [comment]
> By the way, I have tried to run the recommended command for updating documentation but ran into this error. I'm not quite sure what to make of it honestly, but I'm happy to try again if there's any suggestions on what to check.
> 
> ```
> $ yarn generate-docs
> yarn run v1.22.10
> $ typedoc --out docs src
> Info: Loaded plugin typedoc-plugin-markdown
> Error: Tried to set an option (module) that was not declared.
> Error: Tried to set an option (mode) that was not declared.
> Error: Tried to set an option (target) that was not declared.
> Error: Tried to set an option (hideSources) that was not declared.
> Error: Tried to set an option (includeDeclarations) that was not declared.
> error Command failed with exit code 1.
> ```

This is caused by me upgrading to a newer version of `typedoc`, but without adding the changes required to run this new version. Sorry about that!

Also, sorry about taking so much time to get back to you! Thank you for submitting this pull request, that's awesome! 🎉 I'll be reviewing this hopefully tomorrow!

/cc @ryancole

**Review by cobraz — APPROVED** [review]
Thank you so much! This looks very good, and a nice addition to the project!

**Comment by pseudoramble** [comment]
No worries. I fixed the merge issue and a warning I introduced by accident. Once the validations re-run though I'm ready to merge this in when you are!

**Comment by cobraz** [comment]
@pseudoramble I forgot to fix your PR title before merging, so this change was released as 1.2.1 (caused by the way `semantic-release` is wired).

**Pull request merged**
