### PR TITLE
feat: Changed removeUser to signoutRedirect

### PR DESCRIPTION
**Pull request by lclc98**
Changed removeUser to signoutRedirect.
signoutRedirect already calls removeUser so it doesn't need to be called. 
This should solve #20

### CODE REVIEW

**Comment by cobraz** [comment]
Hello 👋 

Thank you so much for contributing to this project!

This would be breaking changes, and I don’t think we need it to be. Meaning, maybe we can add this in instead of replacing it?

If there is a if statement with input either as a configurable variable or input to our sign out function, it would be great. That way people can choose what they want to use.

PS: I’m currently sick (fortunately not COVID—9), so I’m only checking in through my phone. I would happily add an example implementation, but it is difficult.

Thank you again 🙏

**Comment by lclc98** [comment]
Would adding a boolean to signOut (which defaults to false) work?

**Comment by cobraz** [comment]
That sounds good!

**Comment by cobraz** [comment]
Thank you very much for your addition! In order to release this, we need to add commits according to conventional commit messages. However, I'll add this into our alpha branch now, and add that in and also add documentation for this change. You can expect it to be released very soon! :)

**Pull request merged**
