### PR TITLE
fix: initUserManager in AuthContext called every render call

### PR DESCRIPTION
**Pull request by FreeFrags**
Code change for #763

### CODE REVIEW

**Review by braaar — APPROVED** [review]

**Comment by braaar** [comment]
Looks good, thanks!

**Comment by superslau** [comment]
This PR seems to fix an issue I'm having where I see multiple concurrent requests to the OP which results in random behaviour in my app. Is it possible to get a new release? @braaar @cobraz

**Comment by braaar** [comment]
> This PR seems to fix an issue I'm having where I see multiple concurrent requests to the OP which results in random behaviour in my app. Is it possible to get a new release? @braaar @cobraz

Release please was not working, but I think maybe https://github.com/bjerkio/oidc-react/commit/0df3cab516a8fee90ec4e09c8589940a536c54d1 could have fixed the issue. Let's give it a shot and see if we can't trigger and run a successful release

**Comment by braaar** [comment]
Well. [That didn't work](https://github.com/bjerkio/oidc-react/runs/4896712825?check_suite_focus=true). Tracking this in #785

**Comment by superslau** [comment]
Thanks @braaar will follow progress in #785

**Pull request merged**
