### PR TITLE
chore: inline source maps

### PR DESCRIPTION
**Pull request by TheDome**
This fixes an issue where builds would not compile cleanly since the source maps reference the sources directory which is not present in the packaged module.

### CODE REVIEW

**Comment by haritzsaiz** [comment]
Any updates with the PR?

**Comment by simenandre** [comment]
Hello! Thank you for opening this PR.

I'm not sure I understand this enough, but from what I know #991, the issue is that in [our sourcemap](https://www.runpkg.com/?oidc-react@4.0.0/build/src/index.js.map) there are references to `../../src` which is not packed with the NPM package which causes issues (or at least lousy error messages). This PR wants to add the source maps inline, so they are no longer separate files (which means the files are no longer individual).

My initial thought is that isn't there a way to fix that reference? Seeing as the source maps are packed, but in a separate folder? Is there a side effect of adding source maps inline, bundle size? Compatibility? I am not very familiar with the use of inline source maps, so pardon my questions :)

**Comment by TheDome** [comment]
Hi there! Sorry for this late answer. GitHub doesn't do a great Job on notifying me.. 
My problem is currently, that my react project DOES indeed compile. However webpack produces errors since it cannot find the types referenced here. 
Source maps are simple comments (usually) at the end of the file. These comments give browsers a hint how to process this code into its original form.
Usually browsers do not require this information except you look into the debug view where it can be beneficial for debugging purposes. 

There should also be the option to fix this reference by including the sources into the source maps. 
This can be achieved by setting 
```json
    "sourceMap": true,
    "inlineSources": true
```
which will put all sources into the `.map` files. This however is your decision!

Regarding your concerns: 
- I guess there is as you already proposed the side effect, that the node module will be bigger since we effectively add a comment with the contents of the source files. However this is just a comment and AFAIK webpack should be able to remove it. 
  - In detail we are talking about roughly 2kb packaged and 12kb unpackaged more. However when you configure your react installation correctly (which it AFAIK is by default) webpack will not include any source maps into the sources and will instead generate .map files anyways!
- Compatibility: Usually this is just a comment. However I could potentially see the Impact, that a User does not use this package as intended by the typings. Currently webpack would still compile this. However when typings are available, webpack might reject code that has been working since the typings are now available.

**Comment by TheDome** [comment]
I changed the inline source Maps to inline sources (which would add the .map files again!)

**Pull request merged**
