### PR TITLE
feat: Add signInPopup method

### PR DESCRIPTION
**Pull request by Maxinger15**
Hello,
I need the function to open a Popup instead of being redirected. I added this function to the AuthContext.
It uses the functions provided by the UserManager.
If there is something unclear or I missed something just tell me and I fix it.
I exposed the loadUserInfo to be set by the user. Default is true

Issues: #235 #477

### CODE REVIEW

**Comment by Maxinger15** [comment]
I just saw yarn generate-docs throws an error. 
image
I am not familiar with this tool. The error in the console is useless. Just error Comand failed with exit code 1.
Can someone have a look where the problem is?

**Comment by cobraz** [comment]
@Maxinger15 Do you mind adding some tests for this as well? :)

**Comment by Maxinger15** [comment]
@cobraz For what part of the code do you have that in mind? I already added a test that looks if the functions signPopupCallback and signinPopup methods from the usermanager gets called and thats basically all the new codes does.

**Comment by cobraz** [comment]
Codecov has information about that: https://github.com/bjerkio/oidc-react/pull/479#issuecomment-779341143

**Comment by Maxinger15** [comment]
Is that impacted by the covered lines? Because there when I run the test only the lines 122-123 are uncovered and that lines are not from me.

**Review by ryancole — APPROVED** [review]
Looks good to me. I don't see anything that would break existing functionality.

**Review by cobraz — APPROVED** [review]
Looks good to me. We'll need to add tests for this added functionality, but we can do that later :)

**Pull request merged**
