### PR TITLE
fix: Export AuthContextInterface interfaces again

### PR DESCRIPTION
**Pull request by ryancole**
Some point after the 1.0-alpha.5 release a breaking change was introduced that got rid of the type exports from `AuthContextInterface`. I think the types moved around but the export wasn't fixed up. This patch just re-introduces those exports - namely the `AuthProviderProps` type.

### CODE REVIEW

**Comment by ryancole** [comment]
I didn't manually or directly edit all 4 of the included changed files. I only edited the `index.ts` file. I think the other edits are because I pulled upstream into my previous fork. If you'd prefer, I can create a clean fork which should condense this patch down into a single changed file if that feels better.

**Comment by cobraz** [comment]
Thanks again, for yet another pull request! 🙏 

We should probably add some script so we get changelogs and stuff back to `develop` once a release is done. I'll do that manually now, so those changes are in `develop`, but I'd appreciate if you could generate some docs in this PR?

**Comment by cobraz** [comment]
Changes are pushed to `develop` now, so you can clean up your branch now :)

**Comment by ryancole** [comment]
@cobraz I rebased my branch, so it's a bit cleaner now. I didn't notice that there's no package-lock.json in develop branch, so I just deleted that. I use npm instead of yarn. Regarding the docs, the docs for the interfaces already all exist - I just exported the types from `index.ts`. In a previous build, they were exported from there but got removed somewhere along the way.

**Pull request merged**
