### PR TITLE
feat: Add state to signinRedirect.

### PR DESCRIPTION
**Pull request by laurakutovaja**
This solution should solve the issue with redirect described [here](https://github.com/bjerkio/oidc-react/issues/887#issue-1344620630).

### CODE REVIEW

**Review by cobraz — APPROVED** [review]
Thank you! Looks good 🤌

**Comment by AlexanderKositsyn** [comment]
When will it be released?

**Comment by cobraz** [comment]
> When will it be released? @cobraz

Hopefully, we'll be able to ship this on the 25th of October. I've prepared now, see #918

**Comment by zfy171** [comment]
npm 上最新版本仍未2.0.3 是否这个修复未发布

**Comment by AlexanderKositsyn** [comment]
Any update?

**Pull request merged**
